resources:
  - name: branch-script
    type: git
    icon: github-circle
    source:
      uri: https://github.com/phturb/concourse-multibranch-autopipeline.git
  - name: my-pipeline
    type: concourse-pipeline
    icon: pipe
    source:
      target: http://localhost:8080/
      teams:
        - name: main
          username: test
          password: test

jobs:
  - name: multibranch-pipeline-generator
    public: true
    plan:
      - get: branch-script
        trigger: true
      - get: my-pipeline
      - task: create-branch-pipeline
        config:
          inputs:
            - name: branch-script
          outputs:
            - name: pipeline
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: emeraldsquad/alpine-scripting
          params:
            GIT_REPO: git
          run:
            dir: ./branch-script
            path: sh
            args:
              - ./check-branch.sh
      - put: my-pipeline
        params:
          pipelines:
            - name: test
              team: main
              config_file: pipeline/new_pipeline.yaml
