resource_types:
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: branch-script
    type: git
    icon: github-circle
    source:
      uri: https://github.com/phturb/concourse-multibranch-autopipeline.git
  - name: my-pipeline
    type: concourse-pipeline
    icon: pipe
    source:
      target: "http://172.20.0.3:8080"
      insecure: "true"
      teams:
        - name: main
          username: test
          password: test

jobs:
  - name: multibranch-pipeline-generator
    public: true
    plan:
      - get: branch-script
        trigger: true
      - get: my-pipeline
      - task: create-branch-pipeline
        config:
          inputs:
            - name: branch-script
          outputs:
            - name: pipeline
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ddphilippeturner/alpine-python-script
              tag: "1.0"
          params:
            GIT_REPO: git
            PROJECT: phturb
            REPO: concourse-multibranch-autopipeline
          run:
            dir: ./branch-script
            path: python
            args:
              - main.py
      - put: my-pipeline
        params:
          pipelines:
            - name: test
              team: main
              config_file: pipeline/new_pipeline.yaml
