resources:
  - name: branch-script
    type: git
    icon: github-circle
    source:
      uri: https://github.com/phturb/concourse-multibranch-autopipeline.git
  - name: task-git
    type: git
    icon: file-document-outline
    source:
      uri: https://github.com/phturb/concourse-multibranch-autopipeline.git

jobs:
  - name: multibranch-pipeline-generator
    public: true
    plan:
      - get: branch-script
      - get: task-git
      - task: create-branch-pipeline
        file: task-git/task-maker.yaml
  - name: other-group-task
    public: true
    plan:
      - config:
        path: echo
        args:
          - HelloWorld

groups:
  - name: dev
    jobs:
      - multibranch-pipeline-generator
  - name: other
    jobs:
      - other-group-task
