resources:
  - name: branch-script
    type: git
    icon: github-circle
    source:
      uri: https://github.com/phturb/concourse-multibranch-autopipeline.git

jobs:
  - name: multibranch-pipeline-generator
    public: true
    plan:
      - get: branch-script
        trigger: true
      - task: create-branch-pipeline
        config:
          inputs:
            - name: branch-script
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ddphilippeturner/apline-python-script
          params:
            GIT_REPO: git
          run:
            dir: ./branch-script
            path: sh
            args:
              - ./check-branch.sh
